# 운영환경 설정
# application-prod.properties

# 데이터베이스 연결 설정
spring.datasource.url=ENC(eayPcDh6+3WAeHUTlYfFRPMwpu+Jaf/QhrCFuneM4XjSjALnDzJx7trQZXBrCzY6lJxSyNYy5d4=)
spring.datasource.username=ENC(Fd38nA8wFfyH4/l2LrdkqQ==)
spring.datasource.password=ENC(n/IEbZt6HIjaGZfS7+T0XlX9uK6A2ZZj)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 서버 설정
server.port=80

# 로깅 설정
logging.level.root=WARN

# 주의: 운영 환경에서는 반드시 JASYPT_ENCRYPTOR_PASSWORD 환경 변수를 설정해야 합니다
# spring.datasource.username은 암호화되어 있습니다
# spring.datasource.password은 암호화되어 있습니다
